### ISSUE TITLE
I/O 로직 개선

### ISSUE THREAD

**Issue by namsic** [cheesecrust/raftdb#10]
**Is your feature request related to a problem? Please describe.**

https://github.com/cheesecrust/raftdb/blob/f603a3fa9c5071d691304ad9ac441ceeb1640016/socket.c#L15-L26

현재 위와 같이 처리하고 있습니다. 아래와 같은 문제가 있습니다.
- 표현하려는 데이터에 비해 리소스 사용량이 많습니다.
- 짧은 시간에 요청이 몰리는 상황에서 소켓에 쌓인 데이터를 read하기 전에 상대 노드가 다른 요청을 보내면 일부 요청이 누락될 수 있습니다.

예를 들어, 아래와 같은 시나리오가 발생할 가능성이 있어 보입니다.
1. `Node A`가 다른 노드에게 `REQUEST_VOTE` 전송

2. `Node B`는 `Node A`에게 투표

3. `Node A`가 리더로 승급하고, `HEARTBEAT` 전송

4. 3번까지 진행된 이후에 `Node C`가 `recvfrom()` 호출하면, 아래 데이터가 한 번에 read
`REQUEST_VOTE 1 0HEARTBEAT 1 IP 127.0.0.1 PORT 12345`

5. `Node A`는 REQUEST_VOTE만 처리하고 HEARTBEAT는 무시
   - 빠른 시간 내 다음 HEARTBEAT 받지 못하면 election timeout 발생하여 또 다른 임기 시작될 가능성 있어 보임
   - `Node A`는 이미 leader 된 상태에서 VOTE_GARENTED 받게 되는데, 이러한 처리가 잘 되어 있는지도 의문임

**Describe the solution you'd like**

문자열 대신 bytes 데이터를 사용하여 네트워크를 효율적으로 사용하고 요청을 정확하게 처리할 수 있을 것입니다.

```c
enum request {
    HEARTBEAT = 0,
    REQUEST_VOTE,
    MEMBER_ADD,
    ...
};

// send
char buf[3] = {request.REQUEST_VOTE, term, candidate_id}
sendto(node->socket_fd, buf, 3, 0, (const struct sockaddr*)&addr, len);

// recv
msglen = recvfrom(node->socket_fd, (char*)buffer, 1024, MSG_WAITALL, (struct sockaddr*)&addr, &len);
idx = 0;
while (cursor < msglen) {
    switch (buffer[idx++]) {
        case request.REQUEST_VOTE:
            term = buffer[idx++];
            candidate_id = buffer[idx++];
            // printf("REQUEST_VOTE, term: %d, cand_id: %d\n", term, candidate_id);
            char buf[1] = {request.VOTE_GRANTED};
            sendto(node->socket_fd, buf, 1, 0, (const struct sockaddr*)&addr, len);
            break;
        case request.VOTE_GARNTED:
            // handle vote
        ...
    }
}
```

**Describe alternatives you've considered**
- TCP 전환 검토해야 합니다.

**Additional context**
현재 리더 선출과 관련된 구현이 전반적으로 잘 처리되지 않은 상태로 보입니다.
고정된 member 기준으로 다양한 상황에서 리더 선출 동작에 문제가 없는 것을 확인한 후에
다음 작업(member add, put data, ...)을 진행하는 것이 좋겠습니다.

**Comment by cheesecrust** [comment]
@namsic 
grpc 로 전환하였습니다. 

현재 리더 투표 구현되었고 과거에 문제가 발생했던 재선출로직도 잘 동작합니다.
https://github.com/cheesecrust/goraft/tree/main

**Comment by namsic** [comment]
이후 변경은 PR로 등록하여 제가 리뷰하려고 합니다.
그리고 현재 코드 구조와 동작 방식을 설명 들을 수 있으면 좋겠습니다.
